# Generated by Django 2.1.1 on 2018-12-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_antiga', '0002_registrousuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuarios',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
