# Generated by Django 2.1.1 on 2018-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20181029_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(default=1, upload_to='fotos'),
            preserve_default=False,
        ),
    ]
